version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dino-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
      MYSQL_DATABASE: "dino_ecovision"
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2_data.sql
      - mysql-data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0-alpine
    container_name: dino-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
